### ISSUE TITLE
devel rendering of ema-template images huge

### ISSUE THREAD

**Issue by juhp** [srid/ema-docs#17]
I haven't looked more into this ,but when I run ema-template locally with `ghcid` the ema mascot and footer logo images are rendering in full-screen. I can add a screenshot if it helps, but basically both images are huge: maximized to fill the full width of my desktop browser (both Firefox and Chromium).

The output with the `gen` command looks fine (normal) though - so seems to be something with dev environment.

(Running the `run` command by hand is not supposed to work right, I guess?)

**Comment by srid** [comment]
There were a few changes in this template recently re tailwind 3.0 support.

You should run `foreman start` now. Since you are not using nix, this means you would have to install foreman and tailwind cli manually.

The older approach is still possible btw if you switch to using the cdn shim. 

We should document all of this in Readme.

**Comment by srid** [comment]
The huge images usually indicates missing css (tailwind)

https://github.com/srid/emanote/issues/231

Foreman runner should spawn tailwind and generate the css automatically.

**Comment by srid** [comment]
@juhp actually see the end of readme. This is all documented there. You need `tailwind-haskell` too.

**Comment by srid** [comment]
Just published a new `tailwind-haskell` to hackage. So https://github.com/srid/ema-template#non-nix-workflow should work. If not let me know.
